[build]
  publish = "public"
  functions = "netlify/functions"

# Redirect API calls to the Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Single Page App settings
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200